services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: medical_portal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medical_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:password123@postgres:5432/medical_portal?schema=public"
      JWT_SECRET: "mi-clave-super-secreta-jwt-2024-medical-portal-12345-abcdef"
      PORT: 3001
      FRONTEND_URL: "http://localhost:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - medical_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      VUE_APP_API_URL: "http://localhost:3001/api"
    depends_on:
      - backend
    networks:
      - medical_network

volumes:
  postgres_data:

networks:
  medical_network:
    driver: bridge
