databases:
  - name: medicalportal-postgres
    databaseName: medical_portal
    user: postgres
    region: oregon

services:
  - type: web
    name: medicalportal-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medicalportal-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
